import Head from 'next/head';
import Link from 'next/link';
import Layout, { siteTitle } from '../src/components/layout';


// a* = utilStyles.headingMd
export default function Home() {
  return (
    <Layout home>
      <Head>
        <title>{siteTitle}</title>
      </Head>
      <section className={'a*'}>

        <p>[Your Self Introduction]</p>
        <p>
          (This is a sample website - you’ll be building a site like this on{' '}
          <a href="https://nextjs.org/learn">our Next.js tutorial</a>.)
        </p>

      </section>
    </Layout>
  )
}


// const Home: React.FC = () => {
//   return (
//     <>
//       <Head>
//         <title>vgk-lifestyle</title>
//         <meta name='description' content='Generated by create next app' />
//         <link rel='icon' href='/favicon.ico' />
//       </Head>
//       <main>
//         <div>
//           <h1>
//             Read this:
//             {' '}
//             <Link href="/cards/firstCard"><a>test card</a></Link>
//             {' '}
//             and be delighted!
//           </h1>
//         </div>
//         <br />
//         <div>
//           OR go <a href="https://nhl.com">here.</a>
//         </div>
//         <div>
//           {Card}
//         </div>
//       </main>
//     </>
//   );
// };



// export default Home;
